INSERT INTO EMPLOYEE_SCHEMA_DEFAULT_DATASOURCE VALUES (1, 'Penny');
INSERT INTO EMPLOYEE_SCHEMA_DEFAULT_DATASOURCE VALUES (2, 'Sheldon');
INSERT INTO EMPLOYEE_SCHEMA_DEFAULT_DATASOURCE VALUES (3, 'Amy');
INSERT INTO EMPLOYEE_SCHEMA_DEFAULT_DATASOURCE VALUES (4, 'Leonard');
INSERT INTO EMPLOYEE_SCHEMA_DEFAULT_DATASOURCE VALUES (5, 'Bernadette');
INSERT INTO EMPLOYEE_SCHEMA_DEFAULT_DATASOURCE VALUES (6, 'Raj');
INSERT INTO EMPLOYEE_SCHEMA_DEFAULT_DATASOURCE VALUES (7, 'Howard');
INSERT INTO EMPLOYEE_SCHEMA_DEFAULT_DATASOURCE VALUES (8, 'Priya');